### PR TITLE
fix(IgnoredPages): Comment out / Remove 'UserDefinedForm' from ignoredPages.

### PR DESCRIPTION
**Pull request by SilbinaryWolf**
fix(IgnoredPages): Comment out / Remove 'UserDefinedForm' from ignoredPages.

We don't want the UDF form to be cached and working around the YML for ignoredPages is annoying.
Do you remember why this was added in?

### CODE REVIEW

**Comment by tractorcow** [comment]
It was added in so that validation errors don't get cached, otherwise you can see someone else's errors, which is a privacy concern. :)

**Comment by SilbinaryWolf** [comment]
Isn't that prevented with this?
https://github.com/tractorcow/silverstripe-dynamiccache/blob/master/code/DynamicCache.php#L132

**Comment by tractorcow** [comment]
Oh, I guess so.

Please change your PR to remove instead of comment out the option, and I'll merge.

**Comment by tractorcow** [comment]
Actually make it an empty array.

```yaml
  ignoredPages: []
```

**Comment by SilbinaryWolf** [comment]
Done!

**Pull request merged**
